spring:
  application:
    name: "Client"
  cloud:
    gateway:
      routes:
        - id: "resources"
          uri: "http://resource.localhost:8083/"
          predicates:
            Path=/**
          filters:
            TokenRelay=
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: "http://auth.localhost:9000"
        registration:
          spring:
            provider: "spring"
            client-id: "crm"
            client-secret: "crm"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_basic"
            redirect-uri: "http://client.localhost:8082/login/oauth2/code/spring"
            scope:
              - "user.read"
              - "openid"
              - "user.write"

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        security: trace
