server:
  port: 8083

spring:
  application.name: resource-server
  # the current backend is configured to be used as a resource server
  # then, I must indicate the URI of the backend-auth to be used and which token to be used
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.localhost:9000


logging:
  level:
    org.springframework.security: trace
    org.springframework.web: trace